// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tabloid.Infrastructure.Context;

#nullable disable

namespace Tabloid.Infrastructure.Migrations
{
    [DbContext(typeof(TabDbContext))]
    partial class TabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArtistSong", b =>
                {
                    b.Property<Guid>("ArtistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("ArtistSong");
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenresId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Name", "ArtistId")
                        .IsUnique();

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00ba4053-f280-485a-8c91-6e68a5811670"),
                            Name = "Instrumental"
                        },
                        new
                        {
                            Id = new Guid("06f3a378-1466-4dce-be31-d07bce66b3bf"),
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = new Guid("126a86a1-def6-4d44-9917-b4e23b532502"),
                            Name = "Swing"
                        },
                        new
                        {
                            Id = new Guid("143aa742-966b-4c14-8a3e-45e188e8db88"),
                            Name = "Latino"
                        },
                        new
                        {
                            Id = new Guid("1792b587-515c-4a74-a63c-3cf23b643e4a"),
                            Name = "Blues"
                        },
                        new
                        {
                            Id = new Guid("1bd4fd5e-8906-4e61-8b47-2894a187b218"),
                            Name = "Pop"
                        },
                        new
                        {
                            Id = new Guid("1e295e89-65a8-4d97-b0bb-8a86b8848dbf"),
                            Name = "Rap"
                        },
                        new
                        {
                            Id = new Guid("20d40963-af4b-446e-b56f-88fed4f7ccc5"),
                            Name = "RnB"
                        },
                        new
                        {
                            Id = new Guid("29d81cde-da70-4163-b950-decd69e25f35"),
                            Name = "Hip-hop"
                        },
                        new
                        {
                            Id = new Guid("29ebba88-99a8-4c77-8913-648a4960fbdc"),
                            Name = "Country"
                        },
                        new
                        {
                            Id = new Guid("2b365e69-6d14-4158-adca-e61bc4b6ea1d"),
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = new Guid("2d27174e-6cea-4aed-aea3-795e67a3b6af"),
                            Name = "New wave"
                        },
                        new
                        {
                            Id = new Guid("2e7a36be-ffb0-4966-b283-c61ec7da62ae"),
                            Name = "Soul"
                        },
                        new
                        {
                            Id = new Guid("311c94c8-f483-4a6e-8f1b-277d9c6d9d6e"),
                            Name = "Meme"
                        },
                        new
                        {
                            Id = new Guid("352e4e24-e6d6-4252-a03d-ef59ad1ec24f"),
                            Name = "Anime"
                        },
                        new
                        {
                            Id = new Guid("3575068a-c9cf-48d5-9863-c8a51bded998"),
                            Name = "K-pop"
                        },
                        new
                        {
                            Id = new Guid("3610eea6-f7ed-45ba-ac7e-c12428216b66"),
                            Name = "Rock"
                        },
                        new
                        {
                            Id = new Guid("36b06ce2-4398-4d86-ac2e-85d6671cd65a"),
                            Name = "Hard Rock"
                        },
                        new
                        {
                            Id = new Guid("392e5b99-789f-4a3f-8e62-12b7fa49b50d"),
                            Name = "Alternative Rock"
                        },
                        new
                        {
                            Id = new Guid("39d8b25d-c0b8-480b-9fc4-89b8ac6f4d2e"),
                            Name = "Progressive Rock"
                        },
                        new
                        {
                            Id = new Guid("3a41bba1-de93-4a60-b73c-e6f4c116c974"),
                            Name = "Surf Rock"
                        },
                        new
                        {
                            Id = new Guid("3b48b284-d160-4902-8157-351af90b7dea"),
                            Name = "Indie Rock"
                        },
                        new
                        {
                            Id = new Guid("3e15d1dd-4a5e-43ed-903f-5265eef916ab"),
                            Name = "Psychedelic Rock"
                        },
                        new
                        {
                            Id = new Guid("4b2ce0e5-7ad9-4d49-bbdd-18df8bcd89ac"),
                            Name = "Math Rock"
                        },
                        new
                        {
                            Id = new Guid("4ca16a7b-6d34-4b1a-a712-ba1de65f0490"),
                            Name = "Pop Rock"
                        },
                        new
                        {
                            Id = new Guid("4ea6c397-a74a-454b-96cd-5c332b06a05f"),
                            Name = "Blues Rock"
                        },
                        new
                        {
                            Id = new Guid("5361222c-0e8a-485b-96e6-84758a1f8cf8"),
                            Name = "Reggae Rock"
                        },
                        new
                        {
                            Id = new Guid("5915e7e0-abaa-4448-a38a-11dc5bba281a"),
                            Name = "Jazz Rock"
                        },
                        new
                        {
                            Id = new Guid("61079d22-1773-4f62-a094-dae968ec2523"),
                            Name = "Funk Rock"
                        },
                        new
                        {
                            Id = new Guid("67762cf4-91c2-4bb2-995c-2279f4959f39"),
                            Name = "Industrial Rock"
                        },
                        new
                        {
                            Id = new Guid("688672b4-d039-472d-8f68-0b16b4d21099"),
                            Name = "Punk rock"
                        },
                        new
                        {
                            Id = new Guid("69fbc41b-e2a5-4ee1-a5d6-a901b5ecd2c5"),
                            Name = "Heavy Metal"
                        },
                        new
                        {
                            Id = new Guid("6ac4cd9e-0eac-4397-931a-87c59aadcf3f"),
                            Name = "Avant-Garde Metal"
                        },
                        new
                        {
                            Id = new Guid("6dd672ed-f2d6-4496-ac35-26535fb64933"),
                            Name = "Extreme Metal"
                        },
                        new
                        {
                            Id = new Guid("708d1a13-398e-4b7a-951a-344443762a20"),
                            Name = "Black Metal"
                        },
                        new
                        {
                            Id = new Guid("7303ac90-d829-4eaa-b875-e84789befb20"),
                            Name = "Doom Metal"
                        },
                        new
                        {
                            Id = new Guid("7342426b-440f-48ba-b559-a0ec1dce7918"),
                            Name = "Death Metal"
                        },
                        new
                        {
                            Id = new Guid("75ac8f78-af29-4907-897d-569b200f5b70"),
                            Name = "Thrash Metal"
                        },
                        new
                        {
                            Id = new Guid("78bd8712-345a-420a-adfe-755ebbaca901"),
                            Name = "Crossover Thrash"
                        },
                        new
                        {
                            Id = new Guid("79f91a8e-f9ca-48d7-83e9-501e957079de"),
                            Name = "Punk Metal"
                        },
                        new
                        {
                            Id = new Guid("806c90ad-5dfc-4dd8-b0d6-504bed981cb7"),
                            Name = "Speed Metal"
                        },
                        new
                        {
                            Id = new Guid("823ff86e-c1b4-4adc-b3be-381a6445e01d"),
                            Name = "Glam Metal"
                        },
                        new
                        {
                            Id = new Guid("89c7935d-cbd3-40e1-bddb-5471c3c65d26"),
                            Name = "Groove Metal"
                        },
                        new
                        {
                            Id = new Guid("8c299b0d-f492-4493-9971-6274f3df72d8"),
                            Name = "Power Metal"
                        },
                        new
                        {
                            Id = new Guid("8ee31aa9-9992-4b73-8a46-fc8260dc1d52"),
                            Name = "Symphonic Metal"
                        },
                        new
                        {
                            Id = new Guid("9088cf8e-ba8a-4d04-87e9-f8c6b28072a1"),
                            Name = "Melodic Death Metal"
                        },
                        new
                        {
                            Id = new Guid("933f74f0-2dad-4f18-aa3c-4cb7c2b4e31f"),
                            Name = "Technical Death Metal"
                        },
                        new
                        {
                            Id = new Guid("94608f06-bbba-483c-a874-5d73a6a86819"),
                            Name = "Math Metal"
                        },
                        new
                        {
                            Id = new Guid("94f2dd00-fa92-4d1a-ba9a-a91f5c5e87a2"),
                            Name = "Alternative Metal"
                        },
                        new
                        {
                            Id = new Guid("9818250b-8943-4dda-9773-70976f0f5e63"),
                            Name = "Nu Metal"
                        },
                        new
                        {
                            Id = new Guid("9eb79154-d693-442d-9f3a-5851d5bd409c"),
                            Name = "Folk Metal"
                        },
                        new
                        {
                            Id = new Guid("a2e791b8-f76b-417a-89fa-944e941e71d3"),
                            Name = "Progressive Metal"
                        },
                        new
                        {
                            Id = new Guid("a3afcbd3-58a7-41c8-a14a-1b2ab7c2af4a"),
                            Name = "Djent"
                        },
                        new
                        {
                            Id = new Guid("a530cf67-2101-4957-807a-11de50385706"),
                            Name = "Gothic Metal"
                        },
                        new
                        {
                            Id = new Guid("a7206a81-c107-49b9-83b0-49cd6bd50b77"),
                            Name = "Industrial Metal"
                        },
                        new
                        {
                            Id = new Guid("a8c63f3f-bd3e-4b24-bc51-bdda58dfdcff"),
                            Name = "Neue Deutsche Härte"
                        },
                        new
                        {
                            Id = new Guid("ac0dcd5b-57e2-4033-bb64-5ea8387af0ee"),
                            Name = "Rap Metal"
                        },
                        new
                        {
                            Id = new Guid("bc0eaa4c-4286-4f64-84bf-01a6dd8ec550"),
                            Name = "Sludge Metal"
                        },
                        new
                        {
                            Id = new Guid("bdb370ea-2bc7-4ab9-ba3b-50f15d642444"),
                            Name = "Viking Metal"
                        },
                        new
                        {
                            Id = new Guid("be9f2922-505b-4548-9dd5-dd83e8511f50"),
                            Name = "Pirate Metal"
                        },
                        new
                        {
                            Id = new Guid("c9672803-489c-4041-a847-e0882812f9ba"),
                            Name = "National Socialist Black Metal"
                        },
                        new
                        {
                            Id = new Guid("c98ceb06-0e39-4401-af13-f8195588c612"),
                            Name = "Depressive Suicidal Black Metal"
                        },
                        new
                        {
                            Id = new Guid("cbfcd2ee-006e-405c-a68d-a324c3fc1fe2"),
                            Name = "Red and Anarchist Black Metal"
                        },
                        new
                        {
                            Id = new Guid("cf0ece86-c9d5-4229-b256-d366a8a0a4e1"),
                            Name = "Blackened Heavy Metal"
                        },
                        new
                        {
                            Id = new Guid("cfb80e1c-efcd-4c0c-82da-5251e4b4bdba"),
                            Name = "Metalcore"
                        },
                        new
                        {
                            Id = new Guid("d021debb-afd8-4020-ad69-87a845200ac3"),
                            Name = "Deathcore"
                        },
                        new
                        {
                            Id = new Guid("d1ef7caf-3c8f-442b-baa7-741449cdbb52"),
                            Name = "Mathcore"
                        },
                        new
                        {
                            Id = new Guid("d76f547c-cb1a-483c-9c36-299d49ab6eea"),
                            Name = "Electronicore"
                        },
                        new
                        {
                            Id = new Guid("ec973518-563a-4963-839d-d52add39c0ac"),
                            Name = "Grindcore"
                        },
                        new
                        {
                            Id = new Guid("edbbc352-9d5f-402a-839b-0b0e45626f32"),
                            Name = "Goregrind"
                        },
                        new
                        {
                            Id = new Guid("ef9ec3d2-8781-4943-8aee-fafd726dc927"),
                            Name = "Pornogrind"
                        },
                        new
                        {
                            Id = new Guid("efa82c71-9fc2-49d2-b1b5-a0afc242c928"),
                            Name = "Electro"
                        },
                        new
                        {
                            Id = new Guid("f227bdf6-ae97-476c-adbf-f36fdd9eac11"),
                            Name = "Dubstep"
                        },
                        new
                        {
                            Id = new Guid("f30ee2f7-4372-4e72-a59d-790f1274a3e3"),
                            Name = "Chillstep"
                        },
                        new
                        {
                            Id = new Guid("f38533e8-cb20-4fb4-b7ff-0b2158d9cc1e"),
                            Name = "Glichhop"
                        },
                        new
                        {
                            Id = new Guid("f63b8ea6-617a-4ec7-81fb-ccba1c55211b"),
                            Name = "Ambient"
                        },
                        new
                        {
                            Id = new Guid("f6992f76-c8a2-4485-97db-628d793b84df"),
                            Name = "Wave"
                        },
                        new
                        {
                            Id = new Guid("f6d9b483-53ac-4ba1-93c1-0cc3cfade0e6"),
                            Name = "Lofi"
                        },
                        new
                        {
                            Id = new Guid("f9918a17-66f3-4eaa-8a95-110034717541"),
                            Name = "Drumstep"
                        },
                        new
                        {
                            Id = new Guid("fa1c9b62-b6bc-4f07-a825-a852e34769a1"),
                            Name = "Hardcore"
                        },
                        new
                        {
                            Id = new Guid("fa6a53ff-0fa2-4518-a3af-6bc4cd332ae8"),
                            Name = "House"
                        },
                        new
                        {
                            Id = new Guid("fbc655a7-8125-4ed4-81f9-0c69d8a74685"),
                            Name = "Trap"
                        },
                        new
                        {
                            Id = new Guid("fccc9965-3505-457a-b361-a931dbb20d5c"),
                            Name = "Tance"
                        });
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("FullyMastered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SongNumberInAlbum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Tab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("float");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TuningId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("TuningId");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Tuning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Instrument")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StringNumber")
                        .HasColumnType("int");

                    b.Property<string>("Strings")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Strings")
                        .IsUnique();

                    b.ToTable("Tunings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56e5a0c5-9ba0-4d21-b94c-818808a6222b"),
                            Instrument = 0,
                            Name = "Standard",
                            StringNumber = 6,
                            Strings = "E A D G B e"
                        },
                        new
                        {
                            Id = new Guid("75ecf4ff-66f1-42e3-bdf2-e97da11e99aa"),
                            Instrument = 0,
                            Name = "Drop D",
                            StringNumber = 6,
                            Strings = "D A D G B E"
                        },
                        new
                        {
                            Id = new Guid("fefd4bdb-1b6c-41e2-9e96-9c5eb85b2063"),
                            Instrument = 0,
                            Name = "D# Standard",
                            StringNumber = 6,
                            Strings = "D# G# C# F# A# d#"
                        },
                        new
                        {
                            Id = new Guid("443b7aa5-7ce7-4820-bced-07f571fa9de6"),
                            Instrument = 0,
                            Name = "D Standard",
                            StringNumber = 6,
                            Strings = "D G C F A d"
                        },
                        new
                        {
                            Id = new Guid("e4c7369e-e2df-4659-ad50-c01813395227"),
                            Instrument = 0,
                            Name = "G G C F A d",
                            StringNumber = 6,
                            Strings = "G G C F A d"
                        },
                        new
                        {
                            Id = new Guid("df9bc326-2e5f-4547-9937-4a2a12b010f6"),
                            Instrument = 0,
                            Name = "C# Standard",
                            StringNumber = 6,
                            Strings = "C# F# B E G# c#"
                        },
                        new
                        {
                            Id = new Guid("1949a3e3-c8a1-42c5-92b3-018cda2879b0"),
                            Instrument = 0,
                            Name = "Drop C",
                            StringNumber = 6,
                            Strings = "C G C F A D"
                        },
                        new
                        {
                            Id = new Guid("7ca1b4ae-106d-4469-83c3-670ad778abbe"),
                            Instrument = 0,
                            Name = "Drop C#",
                            StringNumber = 6,
                            Strings = "C# G# C# F# A# D#"
                        },
                        new
                        {
                            Id = new Guid("f3d8ddd3-59a6-4c4f-924e-124261a04852"),
                            Instrument = 0,
                            Name = "C Standard",
                            StringNumber = 6,
                            Strings = "C F A# D# G c"
                        },
                        new
                        {
                            Id = new Guid("092af51d-c7da-4ec7-8782-527112093600"),
                            Instrument = 0,
                            Name = "Drop B",
                            StringNumber = 6,
                            Strings = "B F# B E G# C#"
                        },
                        new
                        {
                            Id = new Guid("835bed98-6e3c-4d6c-8d76-dfd7bc5444af"),
                            Instrument = 0,
                            Name = "B Standard",
                            StringNumber = 6,
                            Strings = "B E A D F# b"
                        },
                        new
                        {
                            Id = new Guid("402a9c32-1c43-41c8-8801-18b1b4a9a936"),
                            Instrument = 0,
                            Name = "Drop A",
                            StringNumber = 6,
                            Strings = "A E A D F# b"
                        },
                        new
                        {
                            Id = new Guid("0642aa55-dcce-49b5-b9e7-6d7b2793d0b3"),
                            Instrument = 0,
                            Name = "Drop A#",
                            StringNumber = 6,
                            Strings = "A# F A# D# G c"
                        },
                        new
                        {
                            Id = new Guid("c18bfdd6-11e2-4ccc-bb8b-0e621e4c1a91"),
                            Instrument = 0,
                            Name = "A Standard",
                            StringNumber = 6,
                            Strings = "A D G C E a"
                        },
                        new
                        {
                            Id = new Guid("db70492e-b7cc-4b18-893b-754ac6aa11f9"),
                            Instrument = 0,
                            Name = "A# Standard",
                            StringNumber = 6,
                            Strings = "A# D# G# C# F a#"
                        },
                        new
                        {
                            Id = new Guid("1b9e3380-5905-413f-9ee9-03fdba8ec50d"),
                            Instrument = 0,
                            Name = "Standard (7-string)",
                            StringNumber = 7,
                            Strings = "B E A D G B e"
                        },
                        new
                        {
                            Id = new Guid("916abb59-5385-403a-bcfe-193c0d35ec8b"),
                            Instrument = 0,
                            Name = "A# Standard (7-string)",
                            StringNumber = 7,
                            Strings = "A# G# C# F# A# d#"
                        },
                        new
                        {
                            Id = new Guid("aa2d36cf-17c9-41c9-8ff6-01f4525b700b"),
                            Instrument = 0,
                            Name = "Drop A (7-string)",
                            StringNumber = 7,
                            Strings = "A E A D G B e"
                        },
                        new
                        {
                            Id = new Guid("cc08baf9-0920-4b2a-90ae-c03b8a744490"),
                            Instrument = 0,
                            Name = "A Standard (7-string)",
                            StringNumber = 7,
                            Strings = "A D G C F A D"
                        },
                        new
                        {
                            Id = new Guid("ef43cb7e-518b-499d-a3f0-598921463bea"),
                            Instrument = 0,
                            Name = "Drop G (7-string)",
                            StringNumber = 7,
                            Strings = "G D G C F A d"
                        },
                        new
                        {
                            Id = new Guid("a8630e44-8bfc-4dbf-bd7c-01d13763d504"),
                            Instrument = 0,
                            Name = "G Standard (7-string)",
                            StringNumber = 7,
                            Strings = "G C F A# D# G C"
                        },
                        new
                        {
                            Id = new Guid("03938ad0-3aad-4021-838d-a14cc974275e"),
                            Instrument = 0,
                            Name = "Open C (7-string)",
                            StringNumber = 7,
                            Strings = "G C G C G C E"
                        },
                        new
                        {
                            Id = new Guid("6fa80499-4a60-48ac-879f-af3e1b04971e"),
                            Instrument = 0,
                            Name = "G C G C F A D (7-string)",
                            StringNumber = 7,
                            Strings = "G C G C F A D"
                        },
                        new
                        {
                            Id = new Guid("9dc963f4-f08b-404b-9314-010ded3aaabd"),
                            Instrument = 0,
                            Name = "Drop E (7-string)",
                            StringNumber = 7,
                            Strings = "E B E A D G B"
                        },
                        new
                        {
                            Id = new Guid("198e52a8-addb-455e-b1c9-abe2dbd5ff80"),
                            Instrument = 0,
                            Name = "Standard (8-string)",
                            StringNumber = 8,
                            Strings = "F# B E A D G B e"
                        },
                        new
                        {
                            Id = new Guid("55e470f3-1717-488d-ac0c-fd28dd0fc7d1"),
                            Instrument = 0,
                            Name = "F Standard (8-string)",
                            StringNumber = 8,
                            Strings = " F A# G# C# F# A# d#"
                        },
                        new
                        {
                            Id = new Guid("02cd609b-3a68-42fc-9f0f-bbc37b9a0e9f"),
                            Instrument = 0,
                            Name = "E Standard (8-string)",
                            StringNumber = 8,
                            Strings = "E A D G C F A D"
                        },
                        new
                        {
                            Id = new Guid("d94c8f44-be87-4e82-8e56-4006eb090bf2"),
                            Instrument = 0,
                            Name = "D# Standard (8-string)",
                            StringNumber = 8,
                            Strings = "D# G# C# F# B E G# d"
                        },
                        new
                        {
                            Id = new Guid("3d1be9c7-81f5-4b88-bd05-29485a8a8136"),
                            Instrument = 0,
                            Name = "A Standard (8-string)",
                            StringNumber = 8,
                            Strings = "A D G C F A D G"
                        },
                        new
                        {
                            Id = new Guid("f7fee790-bae6-4f10-8247-b840afbe9e69"),
                            Instrument = 0,
                            Name = "Drop E (8-string)",
                            StringNumber = 8,
                            Strings = "E B E A D G B e"
                        },
                        new
                        {
                            Id = new Guid("35e41458-e204-4946-82b8-65dd51b6724b"),
                            Instrument = 0,
                            Name = "Drop D# (8-string)",
                            StringNumber = 8,
                            Strings = "D# A# D# G# C# F# A# d#"
                        },
                        new
                        {
                            Id = new Guid("f05291cd-aa6f-4201-9649-81c6fb10e603"),
                            Instrument = 0,
                            Name = "Drop D (8-string)",
                            StringNumber = 8,
                            Strings = "D A D G C F A d"
                        },
                        new
                        {
                            Id = new Guid("4b210eef-9933-4eb7-b4b5-c0aeab64ba27"),
                            Instrument = 1,
                            Name = "Bass Standard",
                            StringNumber = 4,
                            Strings = "E A D G"
                        },
                        new
                        {
                            Id = new Guid("44e2cf1f-df33-45b8-852d-1277eae522a8"),
                            Instrument = 1,
                            Name = "Bass Drop D",
                            StringNumber = 4,
                            Strings = "D A D G"
                        },
                        new
                        {
                            Id = new Guid("afc48f1a-c68d-4984-970d-037cd9b61ac3"),
                            Instrument = 1,
                            Name = "Bass D Standard",
                            StringNumber = 4,
                            Strings = "D G C F"
                        },
                        new
                        {
                            Id = new Guid("fbc8747e-bf8f-471b-81a4-148fb629717e"),
                            Instrument = 1,
                            Name = "Bass Drop C",
                            StringNumber = 4,
                            Strings = "C G C F"
                        },
                        new
                        {
                            Id = new Guid("d1b7cf50-e07f-46b5-88cc-2bce96169579"),
                            Instrument = 1,
                            Name = "Bass C tuned to thirds",
                            StringNumber = 4,
                            Strings = "C F C G"
                        },
                        new
                        {
                            Id = new Guid("1c05a351-92b5-46ab-972a-64f41b1eb69b"),
                            Instrument = 1,
                            Name = "5-string Bass Standard",
                            StringNumber = 5,
                            Strings = "B E A D G"
                        },
                        new
                        {
                            Id = new Guid("8a5a6783-40df-467f-957b-bb2ae731ed4d"),
                            Instrument = 1,
                            Name = "6-string Bass Standard",
                            StringNumber = 5,
                            Strings = "B E A D G C"
                        });
                });

            modelBuilder.Entity("ArtistSong", b =>
                {
                    b.HasOne("Tabloid.Domain.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabloid.Domain.Entities.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("Tabloid.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tabloid.Domain.Entities.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Album", b =>
                {
                    b.HasOne("Tabloid.Domain.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Song", b =>
                {
                    b.HasOne("Tabloid.Domain.Entities.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Tab", b =>
                {
                    b.HasOne("Tabloid.Domain.Entities.Song", "Song")
                        .WithMany("Tabs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tabloid.Domain.Entities.Tuning", "Tuning")
                        .WithMany("Tabs")
                        .HasForeignKey("TuningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("Tuning");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Song", b =>
                {
                    b.Navigation("Tabs");
                });

            modelBuilder.Entity("Tabloid.Domain.Entities.Tuning", b =>
                {
                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
